
package org.choc.demo.cxf.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://demo.choc.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SayYes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SayYes", targetNamespace = "http://demo.choc.org/", className = "org.choc.demo.cxf.proxy.SayYes")
    @ResponseWrapper(localName = "SayYesResponse", targetNamespace = "http://demo.choc.org/", className = "org.choc.demo.cxf.proxy.SayYesResponse")
    public String sayYes();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Say")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Say", targetNamespace = "http://demo.choc.org/", className = "org.choc.demo.cxf.proxy.Say")
    @ResponseWrapper(localName = "SayResponse", targetNamespace = "http://demo.choc.org/", className = "org.choc.demo.cxf.proxy.SayResponse")
    public String say(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
